export const ActionTypes = {
    APPLICATION_LOADING: 'APPLICATION_LOADING',
    APPLICATION_ERROR: 'APPLICATION_ERROR',
    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_CATEGORY: 'GET_CATEGORY',
    SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
    GET_PRODUCT: 'GET_PRODUCT',
    PAGINATE_PRODUCTS: 'PAGINATE_PRODUCTS',
    POST_PRODUCT:'POST_PRODUCT',
    PUT_PRODUCT: 'PUT_PRODUCT', 
    DELETE_PRODUCT: 'DELETE_PRODUCT',
};
